- id: 1
  title: Cappuccino
  description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  image: /assets/images/cappuccino.jpg
  price: 2.99
  weight: 100
  maximum-quantity: 10
  category: coffee
#  url: https://dragonfruit.jekyll-themes.com #URL of the page where the product is present

- id: 2
  title: Espresso
  description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  image: /assets/images/espresso.jpg
  price: 3.99
  weight: 100
  maximum-quantity: 5
  category: coffee


- id: 3
  title: Mocha
  description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  image: /assets/images/black-coffee.jpg
  price: 2.59
  weight: 100
  maximum-quantity: 3
  category: coffee

- id: 4
  title: Oolong Tea
  description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  image: /assets/images/justin-leibow-62-unsplash.jpg
  price: 3.99
  weight: 100
  maximum-quantity: 5
  category: tea

- id: 5
  title: Black Tea
  description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  image: /assets/images/drew-taylor-235558-unsplash.jpg
  price: 4.19
  weight: 100
  maximum-quantity: 5
  category: tea

- id: 6
  title: Fruit Tea
  description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  image: /assets/images/erol-ahmed-305920-unsplash.jpg
  price: 4.59
  weight: 100
  maximum-quantity: 5
  category: tea

- id: 7
  title: Ice Tea
  description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  image: /assets/images/paul-hanaoka-280205-unsplash.jpg
  price: 4.99
  weight: 200
  maximum-quantity: 5
  category: tea
